# config.yml
# 启用调试环境的日志输出
debug: true

# 定时计划（由第三方库 Quartz Jobs 提供支持）
# cron 表达式在线生成工具：
#   https://cron.qqe2.com/
# 本插件已提供的定时计划：
#   now: 即时执行
crontab:
  # 测试用定时计划
  # 每 5 秒执行一次
  test: '/5 * * * * ?'

# 目标服务器组（优先从服务器组内进行匹配并返回，其次才是匹配单个服务器的名称）
# 本插件已提供的目标服务器组：
#   all: 所有服务器
target:
  # 测试用目标服务器
  test:
  - 'test'
  - 'test1'
  - 'test2'

# 自定义占位符（用于替换待发送的文本消息中的指定内容）
# 占位符使用格式：${example_name}
# 本插件已提供的占位符：
#   sender: 发送者名称
#   target: 目标服务器名称（多个名称之间使用 ',' 隔开）
#   target_first: 排在首位的目标服务器名称
#   target_last: 排在末位的目标服务器名称
#   time: 发送消息的时间
placeholder:
  # 设置占位符 time 的时间文本格式
  time: 'yyyy-MM-dd HH:mm:ss'
  # 自定义占位符
  custom:
    # 测试用占位符
    test: '这是一个测试用占位符'
    # 测试用占位符（根据环境动态选择）
    test_env:
      # 【必选】当发送者为服务器时
      server: '服务器'
      # 【必选】当发送者为玩家时
      player: '玩家'
      # 【可选】当发送者为管理员（前提是发送者为玩家）时
      admin: '管理员'
